name: z_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.20.1
  timezone: ^0.10.0

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.ico"

flutter:
  uses-material-design: true
  assets:
    - assets/images/favicon.ico
    - assets/images/ingredients/bayleaves.jpg
    - assets/images/ingredients/BlackPepper.jpg
    - assets/images/ingredients/Coconut Milk.jpg
    - assets/images/ingredients/crushed garlic.jpg
    - assets/images/ingredients/Egg.jpg
    - assets/images/ingredients/eggplants.jpg
    - assets/images/ingredients/onion.jpg
    - assets/images/ingredients/pepper.jpg
    - assets/images/ingredients/peppercorns.jpg
    - assets/images/ingredients/pork belly.jpg
    - assets/images/ingredients/radishes.jpg
    - assets/images/utils/logo.png
    - assets/images/utils/landing-motto.png
    - assets/images/utils/landing-bg-recipe.png
    - assets/images/utils/landing-bg.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
