<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecipesSeeder extends Seeder
{
  public function run()
  {
    DB::table('recipes')->insert([
      [
        'name' => 'Pork Adobo',
        'description' => 'Adobo is widely regarded as the unofficial national dish of the Philippines. This savory recipe typically uses chicken or pork braised in a mix of vinegar, soy sauce, garlic, and spices, resulting in a flavorful, tender meat with a dark, rich sauce. The unique balance of tangy and salty flavors makes it both hearty and comforting, embodying the essence of Filipino cuisine.',
        'category' => json_encode(['Main course']),
        'ingredients' => json_encode(['pork belly', 'soy sauce', 'vinegar', 'crushed garlic', 'peppercorns', 'bay leaves', 'salt', 'water']),
        'country' => 'Philippines',
        'prep_time' => 60,
        'yt_link' => 'https://www.youtube.com/watch?v=OTGASYe7hQk',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Chicken Adobo',
        'description' => 'Adobo is widely regarded as the unofficial national dish of the Philippines. This savory recipe typically uses chicken or pork braised in a mix of vinegar, soy sauce, garlic, and spices, resulting in a flavorful, tender meat with a dark, rich sauce. The unique balance of tangy and salty flavors makes it both hearty and comforting, embodying the essence of Filipino cuisine.',
        'category' => json_encode(['Main course']),
        'ingredients' => json_encode(['chicken', 'onion', 'brown sugar', 'soy sauce', 'vinegar', 'crushed garlic', 'peppercorns', 'bay leaves', 'salt', 'water']),
        'country' => 'Philippines',
        'prep_time' => 60,
        'yt_link' => 'https://www.youtube.com/watch?v=e0Yjljw2awA',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Sinigang na Baboy',
        'description' => 'Sinigang na Baboy is a beloved Filipino sour soup that uses pork as its base, cooked with vegetables like radish, string beans, and eggplant. The key flavor comes from tamarind, which gives the soup its iconic sour taste, making it a warming dish that is perfect for colder days or for relieving the tropical heat. It’s considered a true comfort food that is both nourishing and refreshing.',
        'category' => json_encode(['Main course', 'Soups']),
        'ingredients' => json_encode(['pork belly', 'onion', 'tomatoes', 'radishes', 'eggplants', 'string beans', 'tamarind paste', 'salt', 'pepper', 'water']),
        'country' => 'Philippines',
        'prep_time' => 75,
        'yt_link' => 'https://www.youtube.com/watch?v=Vuk3wly8mxQ',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Halo-Halo',
        'description' => 'Halo-Halo, meaning "mix-mix" in Filipino, is a vibrant and refreshing dessert. It’s made with a mix of shaved ice and milk, along with sweetened fruits, beans, and jellies. Topped with flan, purple yam paste, and sometimes a scoop of ice cream, this dessert is a favorite during hot Philippine summers. Its layers and colors make it a visual delight, and each spoonful offers a different texture and flavor.',
        'category' => json_encode(['Desserts', 'Beverages']),
        'ingredients' => json_encode(['shaved ice', 'sweetened beans', 'nata de coco', 'sweetened jackfruit', 'sweetened banana', 'purple yam paste', 'ice cream', 'evaporated milk']),
        'country' => 'Philippines',
        'prep_time' => 15,
        'yt_link' => 'https://www.youtube.com/watch?v=QfP5Mk8I-co',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Lumpiang Shanghai',
        'description' => 'Lumpiang Shanghai, also known as Filipino spring rolls, are a popular appetizer often served at parties and family gatherings. These crunchy rolls are filled with a savory mixture of ground pork, finely chopped vegetables, and seasonings, wrapped in thin spring roll wrappers, then deep-fried to golden perfection. They’re usually served with a sweet and sour dipping sauce for an extra burst of flavor.',
        'category' => json_encode(['Appetizers', 'Snacks']),
        'ingredients' => json_encode(['ground pork', 'carrot', 'onion', 'garlic', 'egg', 'salt', 'pepper', 'spring roll wrappers', 'oil']),
        'country' => 'Philippines',
        'prep_time' => 45,
        'yt_link' => 'https://www.youtube.com/watch?v=san6M1fGoGw',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Pancit Canton',
        'description' => 'Pancit Canton is a classic Filipino stir-fried noodle dish, loved for its comforting flavors and versatility. Made with wheat noodles, vegetables, and a choice of protein like chicken, pork, or shrimp, Pancit Canton is seasoned with soy sauce and a hint of calamansi for a citrusy twist. This dish is commonly served during birthdays and celebrations as it symbolizes long life and prosperity.',
        'category' => json_encode(['Main course', 'Pasta']),
        'ingredients' => json_encode(['pancit canton noodles', 'chicken breast', 'shrimp', 'cabbage', 'carrot', 'onion', 'garlic', 'soy sauce', 'oyster sauce', 'salt', 'pepper']),
        'country' => 'Philippines',
        'prep_time' => 30,
        'yt_link' => 'https://www.youtube.com/watch?v=9UEv8VlLDOc',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Kare-Kare',
        'description' => 'Kare-Kare is a Filipino stew known for its thick, peanut-based sauce. Traditionally made with oxtail, tripe, and vegetables like eggplant, string beans, and banana blossoms, Kare-Kare is slow-cooked to tender perfection. The creamy, nutty sauce pairs well with bagoong (fermented shrimp paste), which adds a unique salty contrast to the dish’s rich flavors.',
        'category' => json_encode(['Main course']),
        'ingredients' => json_encode(['oxtail', 'peanut butter', 'ground toasted rice', 'eggplant', 'string beans', 'banana blossoms', 'onion', 'salt', 'pepper', 'bagoong']),
        'country' => 'Philippines',
        'prep_time' => 120,
        'yt_link' => 'https://www.youtube.com/watch?v=UVQrw4eNWOs',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Bibingka',
        'description' => 'Bibingka is a traditional Filipino rice cake, typically enjoyed during the holiday season, especially around Christmas. Made from rice flour, coconut milk, and sugar, this fluffy cake is often baked with banana leaves for an added earthy aroma. Topped with salted eggs and cheese, Bibingka is a delicious blend of sweet and savory flavors, with a soft and moist texture that melts in your mouth.',
        'category' => json_encode(['Desserts', 'Baked']),
        'ingredients' => json_encode(['rice flour', 'coconut milk', 'sugar', 'eggs', 'baking powder', 'banana leaves', 'salted egg slices', 'grated cheese']),
        'country' => 'Philippines',
        'prep_time' => 45,
        'yt_link' => 'https://www.youtube.com/watch?v=uJKaKI0s2Vw',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Arroz Caldo',
        'description' => 'Arroz Caldo is a Filipino rice porridge that combines rice, chicken, and ginger, cooked slowly to achieve a creamy texture. This comforting dish is often garnished with fried garlic, scallions, and a squeeze of calamansi for added flavor. Known as a go-to remedy for colds, it’s a warm and soothing meal that’s commonly enjoyed as breakfast or merienda (afternoon snack).',
        'category' => json_encode(['Breakfast', 'Soups']),
        'ingredients' => json_encode(['glutinous rice', 'chicken', 'onion', 'garlic', 'ginger', 'chicken broth', 'salt', 'pepper', 'scallions', 'fried garlic']),
        'country' => 'Philippines',
        'prep_time' => 60,
        'yt_link' => 'https://www.youtube.com/watch?v=CGCaBQGKMXM',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Buko Pandan Salad',
        'description' => 'Buko Pandan Salad is a delightful Filipino dessert made with young coconut strips and pandan-flavored gelatin. Combined with sweetened cream and condensed milk, this creamy salad is chilled to perfection and served as a refreshing dessert, especially during festive gatherings and special occasions. The pandan gives it a distinct aroma and a bright green color, making it visually appealing and irresistibly tasty.',
        'category' => json_encode(['Desserts', 'Salads']),
        'ingredients' => json_encode(['young coconut strips', 'pandan-flavored gelatin', 'condensed milk', 'heavy cream', 'grated cheese']),
        'country' => 'Philippines',
        'prep_time' => 30,
        'yt_link' => 'https://www.youtube.com/watch?v=m2ol9IihZM8',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Turon',
        'description' => 'Turon is a popular Filipino snack made from ripe banana slices and jackfruit wrapped in spring roll wrappers, then deep-fried to a golden crisp. Often coated in caramelized sugar, this treat is loved for its crunchy texture and sweet, fruity filling. Turon is commonly sold as street food in the Philippines and is enjoyed by people of all ages.',
        'category' => json_encode(['Snacks', 'Desserts']),
        'ingredients' => json_encode(['saba bananas', 'jackfruit', 'spring roll wrappers', 'brown sugar', 'oil']),
        'country' => 'Philippines',
        'prep_time' => 20,
        'yt_link' => 'https://www.youtube.com/watch?v=16np55dhV-0',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Chicken Inasal',
        'description' => 'Chicken Inasal is a famous grilled chicken dish from Bacolod, Philippines. Marinated in a mix of calamansi, vinegar, garlic, and lemongrass, it’s then grilled and basted with annatto oil, giving it a vibrant color and a smoky, savory flavor. Served with rice and dipping sauce, Chicken Inasal is loved for its tangy and mildly sweet taste.',
        'category' => json_encode(['Main course']),
        'ingredients' => json_encode(['chicken thighs', 'calamansi juice', 'vinegar', 'garlic', 'lemongrass', 'annatto oil', 'salt', 'pepper']),
        'country' => 'Philippines',
        'prep_time' => 90,
        'yt_link' => 'https://www.youtube.com/watch?v=Y6Ixbef7iRc',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Laing',
        'description' => 'Laing is a flavorful dish from the Bicol region, known for its rich and spicy coconut sauce. Made with dried taro leaves cooked in coconut milk, chilies, and shrimp paste, Laing is often served as a side or main dish, and is loved for its creamy, slightly spicy taste. It’s best enjoyed with rice to balance the bold flavors.',
        'category' => json_encode(['Main course']),
        'ingredients' => json_encode(['dried taro leaves', 'coconut milk', 'shrimp paste', 'garlic', 'ginger', 'onion', 'green chilies', 'salt']),
        'country' => 'Philippines',
        'prep_time' => 60,
        'yt_link' => 'https://www.youtube.com/watch?v=y9k09vX44tA',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Taho',
        'description' => 'Taho is a popular Filipino snack or breakfast item made with soft tofu, arnibal (sweet syrup from brown sugar and vanilla), and sago pearls. Served warm in cups, it’s a comforting, sweet treat often sold by street vendors. The combination of silky tofu and caramel-like syrup makes it a nostalgic favorite for many Filipinos.',
        'category' => json_encode(['Breakfast', 'Beverages']),
        'ingredients' => json_encode(['soft tofu', 'brown sugar', 'water', 'vanilla extract', 'sago pearls']),
        'country' => 'Philippines',
        'prep_time' => 20,
        'yt_link' => 'https://www.youtube.com/watch?v=0Q1q0V3f08A',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Pinakbet',
        'description' => 'Pinakbet is a traditional vegetable stew from the Ilocos region, made with a mix of fresh vegetables like bitter melon, squash, eggplant, and okra. It’s cooked with shrimp paste, which enhances its savory, umami flavor. Pinakbet is typically served as a side dish and is loved for its health benefits and hearty taste.',
        'category' => json_encode(['Main course', 'Side dishes']),
        'ingredients' => json_encode(['bitter melon', 'pork belly', 'squash', 'eggplant', 'okra', 'tomatoes', 'onion', 'garlic', 'shrimp paste', 'salt']),
        'country' => 'Philippines',
        'prep_time' => 40,
        'yt_link' => 'https://www.youtube.com/watch?v=ZTm1LJwNsMg',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'name' => 'Champorado',
        'description' => 'Champorado is a comforting chocolate rice porridge that is enjoyed as breakfast or a snack in the Philippines. Made with glutinous rice and cocoa powder, it’s sweet, creamy, and often topped with condensed milk. Traditionally, it’s also served with salty dried fish (tuyo) on the side, balancing the sweet and salty flavors perfectly.',
        'category' => json_encode(['Breakfast', 'Desserts']),
        'ingredients' => json_encode(['glutinous rice', 'cocoa powder', 'sugar', 'water', 'condensed milk', 'salt']),
        'country' => 'Philippines',
        'prep_time' => 30,
        'yt_link' => 'https://www.youtube.com/watch?v=OKn6DUERXLs',
        'image' => 'default.png',
        'created_at' => now(),
        'updated_at' => now(),
      ]
    ]);
  }
}